/* Location Potential Europe - live city sections. Regenerate: python3 work/make_cities_js.py */
window.LPE_BASE=(function(){var m=location.pathname.match(/^(.*\/location-potential-europe\/)/);return m?m[1]:"/";})();
window.CITIES=[
 {id:"hub",name:"All cities",url:""},
 {id:"uk-london",name:"London",url:"london/"},
 {id:"uk-manchester",name:"Manchester",url:"manchester/"},
 {id:"uk-birmingham",name:"Birmingham",url:"birmingham/"},
 {id:"uk-leeds",name:"Leeds",url:"leeds/"},
 {id:"uk-bristol",name:"Bristol",url:"bristol/"},
 {id:"uk-liverpool",name:"Liverpool",url:"liverpool/"},
 {id:"uk-sheffield",name:"Sheffield",url:"sheffield/"},
 {id:"uk-glasgow",name:"Glasgow",url:"glasgow/"},
 {id:"uk-edinburgh",name:"Edinburgh",url:"edinburgh/"},
 {id:"paris",name:"Paris",url:"paris/"},
 {id:"madrid",name:"Madrid",url:"madrid/"},
 {id:"barcelona",name:"Barcelona",url:"barcelona/"},
 {id:"berlin",name:"Berlin",url:"berlin/"},
 {id:"munich",name:"Munich",url:"munich/"},
 {id:"milan",name:"Milan",url:"milan/"},
 {id:"rome",name:"Rome",url:"rome/"},
 {id:"amsterdam",name:"Amsterdam",url:"amsterdam/"},
 {id:"vienna",name:"Vienna",url:"vienna/"},
 {id:"brussels",name:"Brussels",url:"brussels/"},
 {id:"hamburg",name:"Hamburg",url:"hamburg/"},
 {id:"prague",name:"Prague",url:"prague/"},
 {id:"warsaw",name:"Warsaw",url:"warsaw/"},
 {id:"lisbon",name:"Lisbon",url:"lisbon/"},
 {id:"stockholm",name:"Stockholm",url:"stockholm/"},
 {id:"copenhagen",name:"Copenhagen",url:"copenhagen/"},
 {id:"dublin",name:"Dublin",url:"dublin/"},
 {id:"antwerp",name:"Antwerp",url:"antwerp/"},
 {id:"athens",name:"Athens",url:"athens/"},
 {id:"bucharest",name:"Bucharest",url:"bucharest/"},
 {id:"budapest",name:"Budapest",url:"budapest/"},
 {id:"cologne",name:"Cologne",url:"cologne/"},
 {id:"dusseldorf",name:"Düsseldorf",url:"dusseldorf/"},
 {id:"frankfurt",name:"Frankfurt",url:"frankfurt/"},
 {id:"gothenburg",name:"Gothenburg",url:"gothenburg/"},
 {id:"helsinki",name:"Helsinki",url:"helsinki/"},
 {id:"krakow",name:"Kraków",url:"krakow/"},
 {id:"leipzig",name:"Leipzig",url:"leipzig/"},
 {id:"lyon",name:"Lyon",url:"lyon/"},
 {id:"malaga",name:"Málaga",url:"malaga/"},
 {id:"marseille",name:"Marseille",url:"marseille/"},
 {id:"naples",name:"Naples",url:"naples/"},
 {id:"oslo",name:"Oslo",url:"oslo/"},
 {id:"riga",name:"Riga",url:"riga/"},
 {id:"rotterdam",name:"Rotterdam",url:"rotterdam/"},
 {id:"seville",name:"Seville",url:"seville/"},
 {id:"sofia",name:"Sofia",url:"sofia/"},
 {id:"stuttgart",name:"Stuttgart",url:"stuttgart/"},
 {id:"the-hague",name:"The Hague",url:"the-hague/"},
 {id:"toulouse",name:"Toulouse",url:"toulouse/"},
 {id:"turin",name:"Turin",url:"turin/"},
 {id:"valencia",name:"Valencia",url:"valencia/"},
 {id:"vilnius",name:"Vilnius",url:"vilnius/"},
 {id:"zagreb",name:"Zagreb",url:"zagreb/"},
 {id:"zaragoza",name:"Zaragoza",url:"zaragoza/"},
 {id:"wroclaw",name:"Wrocław",url:"wroclaw/"},
 {id:"lodz",name:"Łódź",url:"lodz/"},
 {id:"poznan",name:"Poznań",url:"poznan/"},
 {id:"dortmund",name:"Dortmund",url:"dortmund/"},
 {id:"essen",name:"Essen",url:"essen/"},
 {id:"duisburg",name:"Duisburg",url:"duisburg/"},
 {id:"bremen",name:"Bremen",url:"bremen/"},
 {id:"dresden",name:"Dresden",url:"dresden/"},
 {id:"nuremberg",name:"Nuremberg",url:"nuremberg/"},
 {id:"hanover",name:"Hanover",url:"hanover/"},
 {id:"palermo",name:"Palermo",url:"palermo/"},
 {id:"genoa",name:"Genoa",url:"genoa/"}
];
(function(){
 const base=window.LPE_BASE, path=location.pathname;
 const cur=(window.CITIES.find(c=>c.url&&path.indexOf(base+c.url)===0)||window.CITIES[0]).id;
 const nav=document.getElementById("citynav");
 if(nav){
  nav.innerHTML='<span class="cn-label cn-full">Best area in the city of:</span><span class="cn-label cn-short">Area:</span>'+window.CITIES.map(c=>
   `<a href="${base+c.url}"${c.id===cur?' class="on"':''}>${c.name}</a>`).join("");
 }
})();
