/* Spanish UI layer for Spanish city pages. Data labels stay in their published English forms. */
(function(){
const T={
"City":"Ciudad","All cities":"Todas las ciudades","Search cities":"Buscar ciudades","Concept":"Concepto","Street":"Calle","Trends":"Tendencias","Opportunity":"Oportunidad","Method":"Método","Rankings":"Rankings","Expert help":"Ayuda experta","Define your concept":"Define tu concepto","The map answers back":"El mapa responde","Top 20 streets for your concept":"Las 20 mejores calles para tu concepto","Pick a preset":"Elige un concepto","See more concepts":"Ver más conceptos","See fewer concepts":"Ver menos conceptos","Filter by category:":"Filtrar por categoría:","All":"Todos","Other — my concept is not listed":"Otro - mi concepto no está en la lista","Save favourite":"Guardar favorito","Saved favourite":"Favorito guardado","Add to compare":"Añadir a comparar","Added to compare":"Añadido a comparar","Slide report":"Informe","Print / save as PDF":"Imprimir / guardar como PDF","Close":"Cerrar","Open the map":"Abrir el mapa","See the top 20":"Ver el top 20","Favourites":"Favoritos","Compare streets":"Comparar calles","Change alerts":"Alertas de cambios","Compare side by side":"Comparar lado a lado","Sources & transparency":"Fuentes y transparencia","Method, sources and limits":"Método, fuentes y límites","No street open yet":"Todavía no has abierto ninguna calle","Planning a real investment?":"¿Estás planificando una inversión real?","Speak to a specialist →":"Hablar con un especialista →","Tell us about your project →":"Cuéntanos tu proyecto →","Request a specialist match →":"Solicitar especialista →","Coffee & brunch":"Café y brunch","Bookshop":"Librería","Florist":"Floristería","Sports bar":"Bar deportivo","Fine dining":"Alta cocina","Fish & chips":"Fish & chips","Vet practice":"Clínica veterinaria","Chinese hotpot":"Hotpot chino","24/7 budget gym":"Gimnasio económico 24/7","Café & coffee":"Café","Restaurants":"Restaurantes","Pubs & bars":"Pubs y bares","Fast food":"Comida rápida","Grocery & food retail":"Alimentación","Fitness & gyms":"Fitness y gimnasios","Workspace":"Espacios de trabajo","Services":"Servicios","Estate agents":"Inmobiliarias","Pharmacy":"Farmacia","Vets":"Veterinarios"};
const phrases=[
[/Start with your concept/gi,"Empieza por tu concepto"],[/Step 1/gi,"Paso 1"],[/Step 2/gi,"Paso 2"],[/Step 3/gi,"Paso 3"],[/Search \d+ cities or countries/gi,"Buscar ciudades o países"],[/See more concepts \((\d+) more\)/gi,"Ver más conceptos ($1 más)"],[/Pick one of the (\d+) presets or start from scratch, then change anything\./gi,"Elige uno de los $1 conceptos o empieza desde cero y cambia lo que necesites."],[/The map and the top-20 table update live with every answer\./gi,"El mapa y el top 20 se actualizan con cada respuesta."],[/Every answer in the Concept tab repaints the map\./gi,"Cada respuesta de la pestaña Concepto actualiza el mapa."],[/The 20 best-matching segments \(areas and streets\), sorted by overall fit for the current concept\./gi,"Los 20 segmentos con mejor ajuste, ordenados para el concepto actual."],[/No matching city/gi,"No hay ciudades coincidentes"]];
function trText(v){let x=T[v]||v;phrases.forEach(([r,n])=>x=x.replace(r,n));return x;}
function walk(root){
 const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;const a=[];while(n=w.nextNode())if(n.parentElement&&!['SCRIPT','STYLE','NOSCRIPT'].includes(n.parentElement.tagName)&&n.nodeValue.trim())a.push(n);a.forEach(n=>{const lead=n.nodeValue.match(/^\s*/)[0],tail=n.nodeValue.match(/\s*$/)[0],core=n.nodeValue.trim(),v=trText(core);if(v!==core)n.nodeValue=lead+v+tail;});
 root.querySelectorAll&&root.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(e=>{e.placeholder=trText(e.placeholder)});
}
walk(document.body);new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)walk(n)}))).observe(document.body,{childList:true,subtree:true});
})();
