/* FR UI layer for FR city pages. Data labels stay in their published English forms. */
(function(){
const T={"City": "Ville", "All cities": "Toutes les villes", "Search cities": "Rechercher une ville", "Concept": "Concept", "Street": "Rue", "Trends": "Tendances", "Opportunity": "Opportunité", "Method": "Méthode", "Rankings": "Classements", "Expert help": "Aide d'expert", "Define your concept": "Définissez votre concept", "The map answers back": "La carte répond", "Top 20 streets for your concept": "Les 20 meilleures rues pour votre concept", "Pick a preset": "Choisir un concept", "See more concepts": "Voir plus de concepts", "See fewer concepts": "Voir moins de concepts", "Filter by category:": "Filtrer par catégorie :", "All": "Tous", "Other — my concept is not listed": "Autre - mon concept n'est pas listé", "Save favourite": "Enregistrer en favori", "Saved favourite": "Favori enregistré", "Add to compare": "Ajouter à la comparaison", "Added to compare": "Ajouté à la comparaison", "Slide report": "Rapport", "Print / save as PDF": "Imprimer / enregistrer en PDF", "Close": "Fermer", "Open the map": "Ouvrir la carte", "See the top 20": "Voir le top 20", "Favourites": "Favoris", "Compare streets": "Comparer les rues", "Change alerts": "Alertes de changement", "Compare side by side": "Comparer côte à côte", "Sources & transparency": "Sources & transparence", "Method, sources and limits": "Méthode, sources et limites", "No street open yet": "Aucune rue ouverte", "Planning a real investment?": "Vous planifiez un vrai investissement ?", "Speak to a specialist →": "Parler à un spécialiste →", "Tell us about your project →": "Parlez-nous de votre projet →", "Request a specialist match →": "Demander un spécialiste →", "Full name": "Nom complet", "Your name": "Votre nom", "Email address": "Adresse e-mail", "Your project": "Votre projet", "Rankings & guides": "Classements & guides", "Expert geomarketing": "Geomarketing expert", "Privacy Notice": "Politique de confidentialité", "Coffee & brunch": "Café & brunch", "Bookshop": "Librairie", "Florist": "Fleuriste", "Sports bar": "Bar sportif", "Fine dining": "Haute cuisine", "Fish & chips": "Fish & chips", "Vet practice": "Cabinet vétérinaire", "Chinese hotpot": "Fondue chinoise", "24/7 budget gym": "Salle de sport économique 24/7", "Café & coffee": "Café", "Restaurants": "Restaurants", "Pubs & bars": "Pubs & bars", "Fast food": "Restauration rapide", "Grocery & food retail": "Alimentation", "Fitness & gyms": "Fitness & salles de sport", "Workspace": "Espaces de travail", "Services": "Services", "Estate agents": "Agences immobilières", "Pharmacy": "Pharmacie", "Vets": "Vétérinaires", "What's missing here?": "Que manque-t-il ici ?", "Street or area": "Rue ou quartier", "Street to test": "Rue à tester", "Opportunity finder": "Détecteur d'opportunités"};
const phrases=[[/Start\ with\ your\ concept/gi,"Commencez par votre concept"],[/Step\ 1/gi,"Étape 1"],[/Step\ 2/gi,"Étape 2"],[/Step\ 3/gi,"Étape 3"],[/Answer\ the\ questionnaire\ below\ first:\ ticket,\ format,\ hours,\ audience\./gi,"Répondez d'abord au questionnaire ci-dessous : ticket moyen, format, horaires, public."],[/The\ map\ and\ the\ top\-20\ table\ update\ live\ with\ every\ answer\./gi,"La carte et le top 20 se mettent à jour à chaque réponse."],[/Every\ answer\ in\ the\ Concept\ tab\ repaints\ the\ map\./gi,"Chaque réponse dans l'onglet Concept met à jour la carte."],[/The\ 20\ best\-matching\ segments\ \(areas\ and\ streets\),\ sorted\ by\ overall\ fit\ for\ the\ current\ concept\./gi,"Les 20 segments (quartiers et rues) les plus adaptés, classés par adéquation globale avec le concept actuel."],[/Markers\ are\ street\ segments\.\ Colour\ =\ fit\ or\ estimated\ revenue\ for\ your\ concept\./gi,"Les marqueurs sont des segments de rue. Couleur = adéquation ou revenu estimé pour votre concept."],[/No\ matching\ city/gi,"Aucune ville correspondante"],[/These\ are\ estimates\ from\ a\ simple\ model\ and\ public\ data\./gi,"Ce sont des estimations issues d'un modèle simple et de données publiques."],[/Save\ streets\ as\ favourites,\ compare\ up\ to\ three\ side\ by\ side/gi,"Enregistrez des rues en favoris, comparez-en jusqu'à trois"]];
function trText(v){let x=T[v]||v;phrases.forEach(([r,n])=>x=x.replace(r,n));return x;}
function walk(root){
 const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;const a=[];while(n=w.nextNode())if(n.parentElement&&!['SCRIPT','STYLE','NOSCRIPT'].includes(n.parentElement.tagName)&&n.nodeValue.trim())a.push(n);a.forEach(n=>{const lead=n.nodeValue.match(/^\s*/)[0],tail=n.nodeValue.match(/\s*$/)[0],core=n.nodeValue.trim(),v=trText(core);if(v!==core)n.nodeValue=lead+v+tail;});
 root.querySelectorAll&&root.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(e=>{e.placeholder=trText(e.placeholder)});
}
walk(document.body);new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)walk(n)}))).observe(document.body,{childList:true,subtree:true});
})();
