const tools=[
{name:'list_cities',description:'List published cities. Optionally filter country or region.',inputSchema:{type:'object',properties:{country:{type:'string'},region:{type:'string'}}}},
{name:'list_concepts',description:'List published business concepts.',inputSchema:{type:'object',properties:{}}},
{name:'get_city_zones',description:'Get evidence-labelled zones in one city.',inputSchema:{type:'object',required:['city'],properties:{city:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}}}},
{name:'rank_zones',description:'Rank zones for a concept, optionally within cities. Scores and revenue are MODELLED.',inputSchema:{type:'object',required:['concept'],properties:{concept:{type:'string'},cities:{type:'array',items:{type:'string'}},limit:{type:'integer',minimum:1,maximum:50}}}},
{name:'explain_zone',description:'Return the OBSERVED, AREA CONTEXT and MODELLED evidence for one zone.',inputSchema:{type:'object',required:['city','zone_id'],properties:{city:{type:'string'},zone_id:{type:'string'}}}},
{name:'compare_zones',description:'Compare up to five zones without removing evidence labels.',inputSchema:{type:'object',required:['zones'],properties:{zones:{type:'array',minItems:2,maxItems:5,items:{type:'object',required:['city','zone_id'],properties:{city:{type:'string'},zone_id:{type:'string'}}}}}}}
];
const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'public, max-age=300'}});
const text=x=>({content:[{type:'text',text:JSON.stringify(x,null,2)}],structuredContent:x});
async function get(base,path){const r=await fetch(base+path,{cf:{cacheTtl:3600,cacheEverything:true}});if(!r.ok)throw new Error('Upstream '+r.status);return r.json();}
function labelledZone(z){return {id:z.id,name:z.name,level:z.level,anchor:{...z.anchor_observed,evidence_label:'OBSERVED'},observed:{...z.observed,evidence_label:'OBSERVED'},area_context:{...z.area_context,evidence_label:'AREA CONTEXT'},modelled:{...z.modelled,evidence_label:'MODELLED'},warning:'Coordinates are shortlist anchors, not premises availability. Verify locally before committing.'};}
async function call(base,name,a){const cat=await get(base,'/api/v1/index.json');
 if(name==='list_cities'){let v=cat.cities;if(a.country)v=v.filter(x=>x.country.toLowerCase()===a.country.toLowerCase());if(a.region)v=v.filter(x=>x.region.toLowerCase()===a.region.toLowerCase());return {cities:v,labels:cat.labels};}
 if(name==='list_concepts')return {concepts:cat.concepts,labels:cat.labels};
 if(name==='get_city_zones'){const d=await get(base,'/api/v1/cities/'+encodeURIComponent(a.city)+'.json');return {city:d.city,zones:d.zones.slice(0,a.limit||50).map(labelledZone),warning:d.warning};}
 if(name==='rank_zones'){const d=await get(base,'/api/v1/concepts/'+encodeURIComponent(a.concept)+'.json');let z=d.zones;if(a.cities&&a.cities.length)z=z.filter(x=>a.cities.includes(x.city_id));z=z.slice().sort((x,y)=>y.fit_modelled-x.fit_modelled).slice(0,a.limit||20).map(x=>({...x,evidence_label:{fit_modelled:'MODELLED',revenue_local_modelled:'MODELLED',revenue_eur_comparison_modelled:'MODELLED',coordinates:'OBSERVED anchor; not premises availability'}}));return {concept:d.concept,zones:z,warning:'Ranking is MODELLED. Read each city record for OBSERVED and AREA CONTEXT evidence.'};}
 if(name==='explain_zone'){const d=await get(base,'/api/v1/cities/'+encodeURIComponent(a.city)+'.json'),z=d.zones.find(x=>x.id===a.zone_id);if(!z)throw new Error('Unknown zone_id');return labelledZone(z);}
 if(name==='compare_zones'){const rows=[];for(const q of a.zones){const d=await get(base,'/api/v1/cities/'+encodeURIComponent(q.city)+'.json'),z=d.zones.find(x=>x.id===q.zone_id);if(!z)throw new Error('Unknown zone_id '+q.zone_id);rows.push({city:d.city,zone:labelledZone(z)});}return {zones:rows,comparison_rule:'Preserve labels. Do not compare MODELLED values as if observed.'};}
 throw new Error('Unknown tool');}
export default{async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-methods':'POST,GET,OPTIONS','access-control-allow-headers':'content-type'}});const url=new URL(req.url),base=env.DATA_BASE;if(req.method==='GET'&&url.pathname==='/')return json({name:'Location Potential MCP',protocol:'MCP JSON-RPC over HTTP',endpoint:'/mcp',tools:tools.map(x=>x.name),evidence_rule:'Every quantitative result preserves OBSERVED, AREA CONTEXT or MODELLED.'});if(req.method!=='POST'||url.pathname!=='/mcp')return json({error:'Not found'},404);let b;try{b=await req.json();let result;if(b.method==='initialize')result={protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'location-potential',version:'1.0.0'}};else if(b.method==='tools/list')result={tools};else if(b.method==='tools/call')result=text(await call(base,b.params.name,b.params.arguments||{}));else if(b.method==='notifications/initialized')return new Response(null,{status:202});else throw new Error('Method not found');return json({jsonrpc:'2.0',id:b.id,result});}catch(e){return json({jsonrpc:'2.0',id:b&&b.id||null,error:{code:-32000,message:e.message}},400);}}};
