"""Generate assets/europe-land.js: a real geographic Europe land outline
projected with the exact same Mercator math as make_frontend_data.py, so city
dots sit on real geography. Source: Natural Earth 1:50m land (public domain).
Run from repo root: python3 pipeline/tools/make_land_js.py
The source GeoJSON is cached in pipeline/data/ (not required in the repo)."""
import json, math, os, urllib.request

SRC = os.path.join("pipeline", "data", "ne_50m_land.geojson")
URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson"
OUT = os.path.join("assets", "europe-land.js")

# --- projection: identical to make_frontend_data.py ---
LON0, LON1, LAT0, LAT1 = -25.0, 45.0, 26.5, 71.5
W = 1000.0
def merc(lat): return math.log(math.tan(math.pi/4 + math.radians(lat)/2))
XW = W / (LON1 - LON0)
def px(lon): return (lon - LON0) * XW
def py(lat): return (merc(LAT1) - merc(lat)) * XW * 180 / math.pi

# kept region: a little beyond the canvas so cut chords stay offscreen
K_LON, K_LAT = (-30.0, 46.0), (25.0, 72.0)
TOL = 1.0          # Douglas-Peucker tolerance in canvas px
MIN_BBOX = 9.0     # drop rings with bbox area below this (px^2) - specks

def dp(points, tol):
    """Douglas-Peucker on [(x,y),...]; returns kept index set."""
    keep = {0, len(points)-1}
    stack = [(0, len(points)-1)]
    while stack:
        a, b = stack.pop()
        if b <= a+1: continue
        ax, ay = points[a]; bx, by = points[b]
        dx, dy = bx-ax, by-ay
        seg = math.hypot(dx, dy)
        worst, wi = -1, None
        for i in range(a+1, b):
            px_, py_ = points[i]
            if seg == 0: d = math.hypot(px_-ax, py_-ay)
            else: d = abs(dy*px_ - dx*py_ + bx*ay - by*ax) / seg
            if d > worst: worst, wi = d, i
        if worst > tol:
            keep.add(wi); stack += [(a, wi), (wi, b)]
    return keep

def main():
    if not os.path.exists(SRC):
        os.makedirs(os.path.dirname(SRC), exist_ok=True)
        print("fetching", URL)
        urllib.request.urlretrieve(URL, SRC)
    fc = json.load(open(SRC, encoding="utf-8"))
    paths = []
    for feat in fc["features"]:
        geom = feat["geometry"]
        polys = [geom["coordinates"]] if geom["type"] == "Polygon" else geom["coordinates"]
        for poly in polys:
            for ring in poly:
                kept = [(lon, lat) for lon, lat in ring
                        if K_LON[0] <= lon <= K_LON[1] and K_LAT[0] <= lat <= K_LAT[1]]
                if len(kept) < 4: continue
                pts = [(px(lon), py(lat)) for lon, lat in kept]
                idx = dp(pts, TOL)
                pts = [p for i, p in enumerate(pts) if i in idx]
                if len(pts) < 4: continue
                xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
                if (max(xs)-min(xs)) * (max(ys)-min(ys)) < MIN_BBOX: continue
                d = "M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z"
                paths.append(d)
    out = ("/* Real land outline of Europe and its surroundings, projected with the same "
           "Mercator math as cities.js (make_frontend_data.py). Source: Natural Earth 1:50m "
           "land (public domain, naturalearthdata.com). Generated by "
           "pipeline/tools/make_land_js.py - do not hand-edit. */\n"
           "window.LPE_LAND=" + json.dumps(paths, separators=(",", ":")) + ";\n")
    open(OUT, "w", encoding="utf-8").write(out)
    print("land written:", len(paths), "rings,", len(out), "bytes ->", OUT)

if __name__ == "__main__":
    main()
