import json,sys,html
sys.path.insert(0,'/home/sandbox/europe/work');from cities_eu import CITIES_EU,SHIP
ROOT='/home/sandbox/europe/repo';SITE='https://millantr97.github.io/location-potential-europe/'
UK=['london','manchester','birmingham','leeds','bristol','liverpool','sheffield','glasgow','edinburgh'];UN={'london':'London','manchester':'Manchester','birmingham':'Birmingham','leeds':'Leeds','bristol':'Bristol','liverpool':'Liverpool','sheffield':'Sheffield','glasgow':'Glasgow','edinburgh':'Edinburgh'}
counts=json.load(open('/home/sandbox/europe/work/seg_counts.json'));eu=[c for c in SHIP if c not in UK];by={}
for c in eu:by.setdefault(CITIES_EU[c]['country_name'].title(),[]).append(c)
def card(c,n,k):return f'<a class="city-card" href="{c}/"><b>{html.escape(n)}</b><span>{counts[k][c]:,} segments</span></a>'
sections=''.join(f'<div class="hub-country"><h3>{html.escape(country)}</h3><div class="city-grid">'+''.join(card(c,CITIES_EU[c]['name'],'eu') for c in sorted(cs,key=lambda x:CITIES_EU[x]['name']))+'</div></div>' for country,cs in sorted(by.items()))
sections+=f'<div class="hub-country"><h3>United Kingdom</h3><div class="city-grid">'+''.join(card(c,UN[c],'uk') for c in UK)+'</div></div>'
n=len(eu)+len(UK);total=sum(counts['eu'].values())+sum(counts['uk'].values())
s=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Location Potential Europe - site selection across {n} cities</title><meta name="description" content="Compare {total:,} street and area segments across {n} European cities. Observed competition, area context and modelled estimates are clearly labelled."><link rel="canonical" href="{SITE}"><meta property="og:title" content="Location Potential Europe - where should your business open?"><meta property="og:url" content="{SITE}"><meta property="og:type" content="website"><link rel="manifest" href="manifest.webmanifest"><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css?v=33"><style>.hub-wrap{{max-width:1080px;margin:0 auto;padding:18px 16px 40px}}.city-grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px;margin:8px 0 22px}}.city-card{{display:block;border:1px solid var(--line);border-radius:10px;padding:10px 12px;text-decoration:none;color:inherit;background:#fff}}.city-card b{{display:block}}.city-card span,.hub-note{{color:var(--muted);font-size:12px}}.hub-country h3{{margin:18px 0 4px;font-size:14px;letter-spacing:.04em;text-transform:uppercase;color:var(--muted)}}</style></head><body><header class="top"><div class="top-row"><div class="brand">Location <span>Potential</span><i class="brand-city">Europe</i></div><nav class="citynav" id="citynav" aria-label="Choose a city"></nav></div></header><main class="hub-wrap"><section class="hero on"><div><div class="eyebrow">Street-level site selection · {n} cities across Europe</div><h1>Where should your business open?</h1><p>Search for a city, describe your concept, and compare <b>{total:,} street and area segments</b>. Every figure is labelled observed, area context or modelled.</p><aside class="truth"><strong>Read the labels, not just the score</strong><p><b class="c-obs">OBSERVED</b> recorded at the street. <b class="c-ctx">AREA CONTEXT</b> nearby residents and demographics. <b class="c-mod">MODELLED</b> transparent estimates. Verify any shortlist locally before signing.</p></aside></div></section><section id="cities"><h2>Choose a city</h2><p class="hub-note">Use the searchable picker above or browse by country.</p>{sections}</section><section id="method"><h2>How the numbers are built</h2><p>Venues, units and station locations come from OpenStreetMap (ODbL). Residents and demographics come from the Eurostat Census 2021 1 km grid. Comparable street-level crime is not shown. Station flow and rents are modelled and labelled. This is a shortlisting tool, not a valuation.</p></section></main><footer class="hub-wrap"><div>Location Potential · Europe · verify shortlists with on-street counts, agent enquiries and licensing checks.</div><a href="privacy.html">Privacy Notice</a></footer><script src="cities.js?v=6"></script><script src="pwa.js?v=1"></script></body></html>'''
open(ROOT+'/index.html','w').write(s);print(n,total)
