# MODELLED occupancy cost per city: typical (not prime) high-street retail rent and office rent,
# in local currency per m2 per year. Calibration anchors: Cushman & Wakefield "Main Streets Across
# the World 2025" prime-street rents (digital report, fetched 13 Sep 2026); typical street modelled
# at ~8-15% of prime, cross-checked against city market reports. Every figure is MODELLED - the
# site's Method tab says so and tells users to get agent quotes. office = office prime typical.
# city: (retail_typical, office_typical, note)
RENTS = {
 'paris':(850,550,'prime CE ~12k+ EUR/sqm/yr'), 'lyon':(320,290,''), 'marseille':(260,240,''),
 'toulouse':(220,230,''), 'bordeaux':(240,250,''), 'lille':(200,220,''), 'nice':(260,240,'Croisette anchor 6,075 prime'),
 'nantes':(190,210,''), 'strasbourg':(200,210,''),
 'madrid':(420,360,'prime Preciados ~3k'), 'barcelona':(380,330,''), 'valencia':(180,190,''),
 'seville':(170,180,''), 'bilbao':(190,200,''), 'malaga':(160,170,''), 'zaragoza':(150,160,''),
 'berlin':(340,420,'Ku-damm prime ~3.5k'), 'munich':(380,480,'Kaufinger prime ~3.7k'),
 'hamburg':(300,340,''), 'cologne':(260,280,'Schildergasse prime ~3k'), 'frankfurt':(280,400,'Zeil prime ~3k'),
 'stuttgart':(250,290,''), 'dusseldorf':(270,320,''), 'leipzig':(160,170,''),
 'rome':(380,350,'Via del Corso anchor ~6k prime'), 'milan':(520,650,'Montenapoleone ~16-20k prime'),
 'naples':(220,200,''), 'turin':(200,210,''), 'florence':(280,280,'Via Roma anchor 6,000 prime'), 'bologna':(210,230,''),
 'amsterdam':(420,450,'Kalverstraat prime ~3k'), 'rotterdam':(240,260,''), 'the-hague':(210,230,''),
 'utrecht':(230,250,''), 'brussels':(330,320,''), 'antwerp':(260,250,''),
 'vienna':(340,300,'Kaerntner Strasse prime ~4k'), 'zurich':(650,700,'Bahnhofstrasse prime ~9k CHF'),
 'geneva':(420,450,''),
 'prague':(380,280,'Na Prikope prime ~2.6k EUR-equiv'), 'budapest':(260,240,''),
 'warsaw':(300,290,''), 'krakow':(220,190,''),
 'lisbon':(280,250,'Chiado prime ~1.7k'), 'porto':(190,180,''),
 'stockholm':(420,500,'Biblioteksgatan prime ~1k EUR-equiv... modelled'), 'gothenburg':(220,240,''),
 'copenhagen':(380,340,'Stroeget prime'), 'helsinki':(280,290,''), 'oslo':(360,420,''),
 'athens':(240,200,'Ermou prime ~2.9k'), 'bucharest':(200,190,''),
 'zagreb':(180,160,''), 'bratislava':(160,150,''), 'ljubljana':(150,140,''), 'sofia':(140,120,''),
 'dublin':(360,600,'Grafton prime ~6k'), 'tallinn':(150,150,''), 'riga':(130,120,''), 'vilnius':(140,130,''),
 'luxembourg':(320,480,''), 'valletta':(170,190,''),

 'liege':(201,222,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'gent':(186,206,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'plovdiv':(211,201,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'varna':(210,200,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'basel':(353,402,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'lausanne':(335,382,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'brno':(3782,3912,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'ostrava':(3580,3703,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'bochum':(181,212,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'wuppertal':(181,212,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'bielefeld':(178,209,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'bonn':(177,208,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'mannheim':(177,207,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'karlsruhe':(176,206,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'munster':(176,206,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'augsburg':(175,205,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'wiesbaden':(174,204,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'gelsenkirchen':(171,201,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'monchengladbach':(171,201,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'aachen':(171,200,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'braunschweig':(170,199,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'kiel':(170,199,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'alicante':(159,176,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'murcia':(157,174,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'palma-de-mallorca':(155,171,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'sabadell':(154,170,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'las-palmas-de-gran-canaria':(152,167,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'santa-cruz-de-tenerife':(151,166,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'pamplona':(149,164,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'granada':(148,163,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'cordoba':(147,162,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'valladolid':(147,162,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'a-coruna':(145,160,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'vigo':(145,160,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'gijon':(142,157,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'vitoria-gasteiz':(141,156,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'san-sebastian':(140,155,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'espoo':(181,212,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'tampere':(175,204,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'montpellier':(182,198,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'grenoble':(178,193,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'rouen':(177,193,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'rennes':(173,188,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'catania':(166,182,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'bari':(156,172,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'verona':(151,165,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'bergamo':(150,165,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'kaunas':(105,115,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'eindhoven':(209,239,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'haarlem':(208,238,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'leiden':(207,236,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'trondheim':(2951,3541,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'gdansk':(540,587,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'szczecin':(518,563,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'lublin':(503,547,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'bydgoszcz':(502,546,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'bialystok':(492,535,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'katowice':(488,531,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'sintra':(137,153,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'iasi':(493,545,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'timisoara':(481,531,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'cluj-napoca':(480,530,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'constanta':(477,527,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'galati':(474,524,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'craiova':(473,523,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'brasov':(470,520,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
 'malmo':(2553,2902,'MODELLED from country typical-city baseline x population tier; verify with local agents'),
}
