# Per-city transit calibration for the MODELLED flow anchor.
# src='wiki': annual rapid-transit ridership (millions) + stations from Wikipedia
#   "List of metro systems" (fetched 13 Sep 2026, https://en.wikipedia.org/wiki/List_of_metro_systems)
#   and "List of tram and light rail transit systems" (stations only for tram networks).
# src='modelled': no published system total in those tables - estimated from network size;
#   Method text on the site explains. ridership_m=None means estimate from stations x per-stop average.
TRANSIT = {
 # city: (ridership_m_annual or None, stations_or_None, mode, src)
 'paris':     (1523.0, 321, 'metro', 'wiki'),   # Paris Metro 2025 (RER extra not counted)
 'lyon':      (230.1, 42, 'metro', 'wiki'),
 'marseille': (76.8, 29, 'metro', 'wiki'),
 'toulouse':  (118.3, 37, 'metro', 'wiki'),
 'lille':     (126.1, 60, 'metro', 'wiki'),
 'berlin':    (554.3, 175, 'u-bahn', 'wiki'),
 'munich':    (452.0, 96, 'u-bahn', 'wiki'),
 'hamburg':   (259.4, 93, 'u-bahn', 'wiki'),
 'nuremberg': (114.4, 49, 'u-bahn', 'wiki'),
 'milan':     (341.0, 125, 'metro', 'wiki'),
 'rome':      (161.5, 74, 'metro', 'wiki'),
 'naples':    (41.1, 31, 'metro', 'wiki'),
 'turin':     (39.0, 23, 'metro', 'wiki'),
 'amsterdam': (110.9, 39, 'metro', 'wiki'),
 'rotterdam': (100.7, 71, 'metro', 'wiki'),
 'vienna':    (404.8, 99, 'u-bahn', 'wiki'),
 'brussels':  (138.3, 59, 'metro', 'wiki'),
 'prague':    (378.8, 61, 'metro', 'wiki'),
 'warsaw':    (197.3, 39, 'metro', 'wiki'),
 'lisbon':    (161.8, 56, 'metro', 'wiki'),
 'stockholm': (462.0, 100, 'metro', 'wiki'),
 'copenhagen':(125.6, 44, 'metro', 'wiki'),
 'helsinki':  (79.0, 30, 'metro', 'wiki'),
 'oslo':      (116.0, 101, 'metro', 'wiki'),
 'budapest':  (382.6, 48, 'metro', 'wiki'),
 'athens':    (240.0, 66, 'metro', 'wiki'),
 'bucharest': (152.0, 64, 'metro', 'wiki'),
 'sofia':     (127.2, 50, 'metro', 'wiki'),
 'bilbao':    (104.5, 42, 'metro', 'wiki'),
 'barcelona': (465.0, 132, 'metro', 'wiki'),
 'madrid':    (715.0, 242, 'metro', 'wiki'),
 # tram/stadtbahn networks: stations observed (wiki tram list), ridership modelled per stop
 'cologne':   (None, 235, 'stadtbahn', 'modelled'),
 'dusseldorf':(None, 99, 'stadtbahn', 'modelled'),
 'stuttgart': (None, 200, 'stadtbahn', 'modelled'),
 'frankfurt': (None, 86, 'u-bahn+stadtbahn', 'modelled'),
 'leipzig':   (None, 510, 'tram', 'modelled'),
 'dublin':    (None, 54, 'luas+dart', 'modelled'),
 'zurich':    (None, 300, 'tram+s-bahn', 'modelled'),
 'geneva':    (None, 76, 'tram', 'modelled'),
 'krakow':    (None, 358, 'tram', 'modelled'),
 'antwerp':   (None, 175, 'tram', 'modelled'),
 'the-hague': (None, 200, 'tram+randstadrail', 'modelled'),
 'utrecht':   (None, 60, 'tram+rail', 'modelled'),
 'porto':     (None, 81, 'light rail', 'modelled'),
 'gothenburg':(None, 133, 'tram', 'modelled'),
 'bordeaux':  (None, 135, 'tram', 'modelled'),
 'nice':      (None, 46, 'tram', 'modelled'),
 'nantes':    (None, 84, 'tram', 'modelled'),
 'strasbourg':(None, 87, 'tram', 'modelled'),
 'seville':   (None, 29, 'metro+tram', 'modelled'),
 'malaga':    (None, 19, 'light rail', 'modelled'),
 'zaragoza':  (None, 11, 'tram', 'modelled'),
 'valencia':  (None, 160, 'metrovalencia', 'modelled'),
 'zagreb':    (None, 256, 'tram', 'modelled'),
 'bratislava':(None, 161, 'tram', 'modelled'),
 'ljubljana': (None, 40, 'rail', 'modelled'),
 'riga':      (None, 227, 'tram', 'modelled'),
 'tallinn':   (None, 41, 'tram', 'modelled'),
 'vilnius':   (None, 20, 'rail', 'modelled'),
 'luxembourg':(None, 24, 'tram+rail', 'modelled'),
 'valletta':  (None, 5, 'bus network', 'modelled'),
 'florence':  (None, 43, 'tram', 'modelled'),
 'bologna':   (None, 10, 'rail', 'modelled'),
}
# modelled per-stop annual ridership (millions) when no published total, by mode
PER_STOP_M = {'stadtbahn':1.1,'tram':0.55,'tram+s-bahn':0.9,'luas+dart':0.9,'light rail':0.8,
 'metro+tram':0.8,'metrovalencia':0.35,'rail':0.5,'tram+rail':0.7,'bus network':0.6,
 'tram+randstadrail':0.6,'u-bahn+stadtbahn':1.6}
