window.CITY={id:"munster",name:"Münster",region:"the Münster urban area",mapCenter:[51.96236,7.62571],mapZoom:12,
cur:"€",cc:"DE",country_name:"Germany",eu:1,
site:"https://millantr97.github.io/location-potential-europe/",siteHost:"millantr97.github.io/location-potential-europe",
texts:{
 flowCredit:"no urban rail system - all flow MODELLED from commercial density",
 police:"",
 voaYear:"modelled 2026",
 voaMethod:`<p>Typical retail and office rents per m² for Münster are MODELLED at city level: anchored to Cushman & Wakefield 'Main Streets Across the World 2025' prime-street rents, scaled down to typical trading streets, cross-checked against local market reports, and shown in local currency. No comparable per-property valuation roll is published across Europe. Always get agent quotes.</p>`,
 crimeNote:"",
 crimeMethod:"",
 crimeDropped:"No comparable open street-level crime feed is published for Germany, so this site does not estimate business crime here.",
 movement:`<p>Typical-day station entries and exits by day type (Mon / Tue-Thu / Fri / Sat / Sun) and annual totals are MODELLED for Münster: the city's published annual urban-rail ridership is divided across the station locations recorded in OpenStreetMap and scaled by each catchment's recorded commercial density, then split across the week on a standard rail-week profile. No stop-level counts are published on a comparable open basis here, so every flow figure on this page is MODELLED - a demand anchor, not a count taken on that pavement. Stations within 900 m from OpenStreetMap. Street-level pitches inherit their parent catchment's flow scaled to the street's share of recorded commercial units; streets beyond 900 m of any station show no flow at all and say so.</p>`,
 resNote:"A 1 km census grid cell describes residents, not the people walking this street.",
 resMethod:`<p>Census 2021 statistics from the Eurostat 1 km population grid for the cell containing the segment anchor: total residents, broad age bands, employed residents and country-of-birth groups (born in Germany / another EU country / outside the EU). The grid does not report employment for France and Germany; there the employment share is a city-level MODELLED figure. The student share is a city-level MODELLED estimate.</p>`,
 resResolution:"Resolution: 1 km census grid cell (Eurostat Census 2021).",
 resCensus:"Census 2021 (1 km grid)",
 resRmini:"A 1 km census grid cell describes residents, not the people walking this street. Census 2021, Eurostat grid.",
 bornAbroad:"Born abroad",
 ageYoung:"Working age (15-64)",
 ageUnder:"Under 15",
 studentsLbl:"Students (city-level est.)",
 profLbl:"Employed residents (share)",
 rentRule:"Rule: city-level typical rent x segment-type factor x footfall factor. City-level MODELLED figure in local currency - always get agent quotes before committing.",
 rentMethod:`<p>The estimated passing rent per m² is MODELLED: a city-level typical high-street rent for Münster (anchored to Cushman &amp; Wakefield 'Main Streets Across the World 2025' prime-street rents, scaled to typical trading streets) x a segment-type factor (prime/managed retail 1.35-1.45, high street 1.15, side street 0.95, market 1.0) x a footfall factor (up to +30% for the busiest flows). No comparable per-property valuation roll is published across Europe, so this stays a city-level estimate in local currency. Always get agent quotes.</p>`,
 coverage:(SEGS,UNITS)=>`<p>${SEGS.length.toLocaleString("en-GB")} segments covering the Münster urban area at street level: ${SEGS.filter(s=>s.lvl!=="street").length} area pitches (curated commercial areas plus urban rail station catchments - flow MODELLED from published system ridership, no minimum flow) and ${SEGS.filter(s=>s.lvl==="street").length.toLocaleString("en-GB")} street pitches - every named retail street and parade with 8 or more recorded commercial units, long streets split into roughly 400 m stretches. ${UNITS.length.toLocaleString("en-GB")} individual commercial units recorded across them from OpenStreetMap. A street pitch inside a station catchment carries that catchment's flow MODELLED down to the street's share of recorded units; a street more than 900 m from any station has no flow anchor and says so on its panel.</p>`,
}};