window.CITY={id:"sydney",name:"Sydney",region:"Greater Sydney",mapCenter:[-33.8688,151.2093],mapZoom:10,
cur:"A$",cc:"AU",country_name:"Australia",eu:0,
site:"https://millantr97.github.io/location-potential-europe/",siteHost:"millantr97.github.io/location-potential-europe",
texts:{
 flowCredit:"Station locations OBSERVED from OpenStreetMap; stop-level flow MODELLED from local commercial density",
 police:"",
 voaYear:"modelled 2026",
 voaMethod:`<p>Typical retail and office rents per m² for Sydney are MODELLED at city level: anchored to Cushman & Wakefield 'Main Streets Across the World 2025' prime-street rents, scaled down to typical trading streets, cross-checked against local market reports, and shown in local currency. A comparable per-property rent roll is not used here. Always get agent quotes.</p>`,
 crimeNote:"",
 crimeMethod:"",
 crimeDropped:"No nationally comparable business-crime feed is used, so this site does not estimate business crime here.",
 movement:`<p>Typical-day station entries and exits by day type (Mon / Tue-Thu / Fri / Sat / Sun) and annual totals are MODELLED for Sydney: station presence is combined with local commercial density across the station locations recorded in OpenStreetMap and scaled by each catchment's recorded commercial density, then split across the week on a standard rail-week profile. No stop-level counts are published on a comparable open basis here, so every flow figure on this page is MODELLED - a demand anchor, not a count taken on that pavement. Stations within 900 m from OpenStreetMap. Street-level pitches inherit their parent catchment's flow scaled to the street's share of recorded commercial units; streets beyond 900 m of any station show no flow at all and say so.</p>`,
 resNote:"An ABS SA1 describes nearby residents, not the people walking this street.",
 resMethod:`<p>ABS Census 2021 statistics from the ABS SA1 containing the segment anchor: total residents, under-18 population, employment, born overseas share and Year 12 completion proxy. These are AREA CONTEXT around the street, not street counts. The student share remains a city-level MODELLED estimate.</p>`,
 resResolution:"Resolution: ABS SA1 (ABS Census 2021).",
 resCensus:"ABS Census 2021 (SA1)",
 resRmini:"An ABS SA1 describes nearby residents, not the people walking this street. ABS Census 2021, Australian Bureau of Statistics.",
 bornAbroad:"Born abroad",
 ageYoung:"Age 18+",
 ageUnder:"Under 18",
 studentsLbl:"Students (city-level est.)",
 profLbl:"Year 12 completion proxy",
 rentRule:"Rule: city-level typical rent x segment-type factor x footfall factor. City-level MODELLED figure in local currency - always get agent quotes before committing.",
 rentMethod:`<p>The estimated passing rent per m² is MODELLED: a city-level typical high-street rent for Sydney (anchored to Cushman &amp; Wakefield 2025 Australian prime-street rents, scaled to typical trading streets) x a segment-type factor (prime/managed retail 1.35-1.45, high street 1.15, side street 0.95, market 1.0) x a footfall factor (up to +30% for the busiest flows). A comparable per-property rent roll is not used here, so this stays a city-level estimate in local currency. Always get agent quotes.</p>`,
 coverage:(SEGS,UNITS)=>`<p>${SEGS.length.toLocaleString("en-GB")} segments covering the Sydney region at street level: ${SEGS.filter(s=>s.lvl!=="street").length} area pitches (curated commercial areas plus urban rail station catchments - flow MODELLED from local commercial density, no minimum flow) and ${SEGS.filter(s=>s.lvl==="street").length.toLocaleString("en-GB")} street pitches - every named retail street and parade with 8 or more recorded commercial units, long streets split into roughly 400 m stretches. ${UNITS.length.toLocaleString("en-GB")} individual commercial units recorded across them from OpenStreetMap. A street pitch inside a station catchment carries that catchment's flow MODELLED down to the street's share of recorded units; a street more than 900 m from any station has no flow anchor and says so on its panel.</p>`,
}};